title: ""
logo: images/bubble_nebula_crop.jpg
author: Luke Conibear
copyright: "2026"
execute:
  execute_notebooks: "off"
sphinx:
  config:
    html_extra_path:
      - .nojekyll
      - slides
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js